default: # 默认连接
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: admin

  # 其他配置
  synchronize: false
  logging: false
  timezone: 0800
  entitiesDir: app/entity # entity 目录
  migrations: [db/migration/**/*.ts]
  subscribers: [app/subscriber/**/*.ts]

  cli: # cli 的操作目录
    entitiesDir: app/entity
    migrationsDir: db/migration
    subscribersDir: app/subscriber

